### ISSUE TITLE
Move rook-ceph into Requirements

### ISSUE THREAD

**Issue by bjw-s** [bjw-s/k8s-gitops#407]
**Context:**
Currently my rook-ceph stuff lives in the `cluster-apps` Kustomization. I should move these to the `cluster-requirements` Kustomization so that any errors in `apps` don't potentially nuke the cluster storage.

**Tasks**
- [ ] Move `rook-ceph` folder from `apps` to `requirements`
- [ ] Set `prune: false` on `cluster-requirements` Kustomization
- [ ] Check if there are any CRD's that need to be manually managed
